#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v19
# autospec commit: 6a4b23bb3e69
#
Name     : google-crc32c
Version  : 1.1.2
Release  : 1
URL      : https://github.com/google/crc32c/archive/1.1.2/crc32c-1.1.2.tar.gz
Source0  : https://github.com/google/crc32c/archive/1.1.2/crc32c-1.1.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: google-crc32c-lib = %{version}-%{release}
Requires: google-crc32c-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# CRC32C
[![Build Status](https://github.com/google/crc32c/actions/workflows/build.yml/badge.svg)](https://github.com/google/crc32c/actions/workflows/build.yml)

%package dev
Summary: dev components for the google-crc32c package.
Group: Development
Requires: google-crc32c-lib = %{version}-%{release}
Provides: google-crc32c-devel = %{version}-%{release}
Requires: google-crc32c = %{version}-%{release}

%description dev
dev components for the google-crc32c package.


%package lib
Summary: lib components for the google-crc32c package.
Group: Libraries
Requires: google-crc32c-license = %{version}-%{release}

%description lib
lib components for the google-crc32c package.


%package license
Summary: license components for the google-crc32c package.
Group: Default

%description license
license components for the google-crc32c package.


%prep
%setup -q -n crc32c-1.1.2
cd %{_builddir}/crc32c-1.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726166769
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DCRC32C_BUILD_BENCHMARKS=OFF \
-DCRC32C_BUILD_TESTS=OFF \
-DCRC32C_USE_GLOG=OFF  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726166769
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/google-crc32c
cp %{_builddir}/crc32c-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/google-crc32c/862c5a5bb5018afa99b974ba097e5e97eab6bd70 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/crc32c/crc32c.h
/usr/lib64/cmake/Crc32c/Crc32cConfig.cmake
/usr/lib64/cmake/Crc32c/Crc32cConfigVersion.cmake
/usr/lib64/cmake/Crc32c/Crc32cTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Crc32c/Crc32cTargets.cmake
/usr/lib64/libcrc32c.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcrc32c.so.1
/usr/lib64/libcrc32c.so.1.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/google-crc32c/862c5a5bb5018afa99b974ba097e5e97eab6bd70
